//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractPanel complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractPanel"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://axelor.com/xml/ns/object-views}AbstractContainer"&gt;
 *       &lt;attribute name="itemSpan" type="{http://www.w3.org/2001/XMLSchema}int" default="6" /&gt;
 *       &lt;attribute name="showFrame" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="sidebar" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="stacked" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="attached" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="onTabSelect" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;anyAttribute processContents='skip'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractPanel")
@XmlSeeAlso({
    Panel.class,
    PanelRelated.class,
    PanelTabs.class,
    PanelEditor.class,
    PanelMail.class,
    ExtendForm.Replace.Panel.class
})
public abstract class AbstractPanel
    extends AbstractContainer
{

    @XmlAttribute(name = "itemSpan")
    protected Integer itemSpan;
    @XmlAttribute(name = "showFrame")
    protected Boolean showFrame;
    @XmlAttribute(name = "sidebar")
    protected Boolean sidebar;
    @XmlAttribute(name = "stacked")
    protected Boolean stacked;
    @XmlAttribute(name = "attached")
    protected Boolean attached;
    @XmlAttribute(name = "onTabSelect")
    protected String onTabSelect;

    /**
     * Gets the value of the itemSpan property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getItemSpan() {
        if (itemSpan == null) {
            return  6;
        } else {
            return itemSpan;
        }
    }

    /**
     * Sets the value of the itemSpan property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setItemSpan(Integer value) {
        this.itemSpan = value;
    }

    /**
     * Gets the value of the showFrame property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowFrame() {
        if (showFrame == null) {
            return true;
        } else {
            return showFrame;
        }
    }

    /**
     * Sets the value of the showFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowFrame(Boolean value) {
        this.showFrame = value;
    }

    /**
     * Gets the value of the sidebar property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSidebar() {
        return sidebar;
    }

    /**
     * Sets the value of the sidebar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSidebar(Boolean value) {
        this.sidebar = value;
    }

    /**
     * Gets the value of the stacked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isStacked() {
        return stacked;
    }

    /**
     * Sets the value of the stacked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStacked(Boolean value) {
        this.stacked = value;
    }

    /**
     * Gets the value of the attached property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAttached() {
        return attached;
    }

    /**
     * Sets the value of the attached property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAttached(Boolean value) {
        this.attached = value;
    }

    /**
     * Gets the value of the onTabSelect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnTabSelect() {
        return onTabSelect;
    }

    /**
     * Sets the value of the onTabSelect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnTabSelect(String value) {
        this.onTabSelect = value;
    }

}
