//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractGridView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractGridView"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://axelor.com/xml/ns/object-views}AbstractView"&gt;
 *       &lt;choice&gt;
 *         &lt;sequence maxOccurs="unbounded"&gt;
 *           &lt;element name="extend" type="{http://axelor.com/xml/ns/object-views}ExtendGrid" maxOccurs="unbounded"/&gt;
 *         &lt;/sequence&gt;
 *         &lt;sequence&gt;
 *           &lt;element name="help" type="{http://axelor.com/xml/ns/object-views}Help" minOccurs="0"/&gt;
 *           &lt;element name="toolbar" type="{http://axelor.com/xml/ns/object-views}Toolbar" minOccurs="0"/&gt;
 *           &lt;element name="menubar" type="{http://axelor.com/xml/ns/object-views}Menubar" minOccurs="0"/&gt;
 *           &lt;element name="hilite" type="{http://axelor.com/xml/ns/object-views}Hilite" maxOccurs="unbounded" minOccurs="0"/&gt;
 *           &lt;choice maxOccurs="unbounded"&gt;
 *             &lt;group ref="{http://axelor.com/xml/ns/object-views}GridWidgets"/&gt;
 *           &lt;/choice&gt;
 *         &lt;/sequence&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="expandable" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="sortable" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="orderBy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="groupBy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="x-row-height" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="x-col-width" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="x-no-fetch" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="x-selector"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="checkbox"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="edit-icon" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" /&gt;
 *       &lt;attribute name="onNew" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="canNew" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="canEdit" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="canSave" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="canDelete" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="canArchive" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="canMove" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractGridView", propOrder = {
    "extend",
    "help",
    "toolbar",
    "menubar",
    "hilite",
    "fieldOrButton"
})
@XmlSeeAlso({
    GridView.class,
    NestedGridView.class
})
public abstract class AbstractGridView
    extends AbstractView
{

    protected List<ExtendGrid> extend;
    protected Help help;
    protected Toolbar toolbar;
    protected Menubar menubar;
    protected List<Hilite> hilite;
    @XmlElements({
        @XmlElement(name = "field", type = GridField.class),
        @XmlElement(name = "button", type = GridButton.class)
    })
    protected List<SimpleWidget> fieldOrButton;
    @XmlAttribute(name = "expandable")
    protected Boolean expandable;
    @XmlAttribute(name = "sortable")
    protected Boolean sortable;
    @XmlAttribute(name = "orderBy")
    protected String orderBy;
    @XmlAttribute(name = "groupBy")
    protected String groupBy;
    @XmlAttribute(name = "x-row-height")
    protected Integer xRowHeight;
    @XmlAttribute(name = "x-col-width")
    protected Integer xColWidth;
    @XmlAttribute(name = "x-no-fetch")
    protected Boolean xNoFetch;
    @XmlAttribute(name = "x-selector")
    protected String xSelector;
    @XmlAttribute(name = "edit-icon")
    protected Boolean editIcon;
    @XmlAttribute(name = "onNew")
    protected String onNew;
    @XmlAttribute(name = "canNew")
    protected String canNew;
    @XmlAttribute(name = "canEdit")
    protected String canEdit;
    @XmlAttribute(name = "canSave")
    protected Boolean canSave;
    @XmlAttribute(name = "canDelete")
    protected Boolean canDelete;
    @XmlAttribute(name = "canArchive")
    protected Boolean canArchive;
    @XmlAttribute(name = "canMove")
    protected Boolean canMove;

    /**
     * Gets the value of the extend property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the extend property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExtend().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtendGrid }
     * 
     * 
     */
    public List<ExtendGrid> getExtend() {
        if (extend == null) {
            extend = new ArrayList<ExtendGrid>();
        }
        return this.extend;
    }

    /**
     * Gets the value of the help property.
     * 
     * @return
     *     possible object is
     *     {@link Help }
     *     
     */
    public Help getHelp() {
        return help;
    }

    /**
     * Sets the value of the help property.
     * 
     * @param value
     *     allowed object is
     *     {@link Help }
     *     
     */
    public void setHelp(Help value) {
        this.help = value;
    }

    /**
     * Gets the value of the toolbar property.
     * 
     * @return
     *     possible object is
     *     {@link Toolbar }
     *     
     */
    public Toolbar getToolbar() {
        return toolbar;
    }

    /**
     * Sets the value of the toolbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Toolbar }
     *     
     */
    public void setToolbar(Toolbar value) {
        this.toolbar = value;
    }

    /**
     * Gets the value of the menubar property.
     * 
     * @return
     *     possible object is
     *     {@link Menubar }
     *     
     */
    public Menubar getMenubar() {
        return menubar;
    }

    /**
     * Sets the value of the menubar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Menubar }
     *     
     */
    public void setMenubar(Menubar value) {
        this.menubar = value;
    }

    /**
     * Gets the value of the hilite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hilite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHilite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hilite }
     * 
     * 
     */
    public List<Hilite> getHilite() {
        if (hilite == null) {
            hilite = new ArrayList<Hilite>();
        }
        return this.hilite;
    }

    /**
     * Gets the value of the fieldOrButton property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldOrButton property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldOrButton().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GridField }
     * {@link GridButton }
     * 
     * 
     */
    public List<SimpleWidget> getFieldOrButton() {
        if (fieldOrButton == null) {
            fieldOrButton = new ArrayList<SimpleWidget>();
        }
        return this.fieldOrButton;
    }

    /**
     * Gets the value of the expandable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isExpandable() {
        return expandable;
    }

    /**
     * Sets the value of the expandable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setExpandable(Boolean value) {
        this.expandable = value;
    }

    /**
     * Gets the value of the sortable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSortable() {
        return sortable;
    }

    /**
     * Sets the value of the sortable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSortable(Boolean value) {
        this.sortable = value;
    }

    /**
     * Gets the value of the orderBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderBy() {
        return orderBy;
    }

    /**
     * Sets the value of the orderBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderBy(String value) {
        this.orderBy = value;
    }

    /**
     * Gets the value of the groupBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupBy() {
        return groupBy;
    }

    /**
     * Sets the value of the groupBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupBy(String value) {
        this.groupBy = value;
    }

    /**
     * Gets the value of the xRowHeight property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getXRowHeight() {
        return xRowHeight;
    }

    /**
     * Sets the value of the xRowHeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setXRowHeight(Integer value) {
        this.xRowHeight = value;
    }

    /**
     * Gets the value of the xColWidth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getXColWidth() {
        return xColWidth;
    }

    /**
     * Sets the value of the xColWidth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setXColWidth(Integer value) {
        this.xColWidth = value;
    }

    /**
     * Gets the value of the xNoFetch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXNoFetch() {
        return xNoFetch;
    }

    /**
     * Sets the value of the xNoFetch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXNoFetch(Boolean value) {
        this.xNoFetch = value;
    }

    /**
     * Gets the value of the xSelector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXSelector() {
        return xSelector;
    }

    /**
     * Sets the value of the xSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXSelector(String value) {
        this.xSelector = value;
    }

    /**
     * Gets the value of the editIcon property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isEditIcon() {
        if (editIcon == null) {
            return true;
        } else {
            return editIcon;
        }
    }

    /**
     * Sets the value of the editIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditIcon(Boolean value) {
        this.editIcon = value;
    }

    /**
     * Gets the value of the onNew property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnNew() {
        return onNew;
    }

    /**
     * Sets the value of the onNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnNew(String value) {
        this.onNew = value;
    }

    /**
     * Gets the value of the canNew property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanNew() {
        return canNew;
    }

    /**
     * Sets the value of the canNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanNew(String value) {
        this.canNew = value;
    }

    /**
     * Gets the value of the canEdit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanEdit() {
        return canEdit;
    }

    /**
     * Sets the value of the canEdit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanEdit(String value) {
        this.canEdit = value;
    }

    /**
     * Gets the value of the canSave property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanSave() {
        return canSave;
    }

    /**
     * Sets the value of the canSave property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanSave(Boolean value) {
        this.canSave = value;
    }

    /**
     * Gets the value of the canDelete property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanDelete() {
        return canDelete;
    }

    /**
     * Sets the value of the canDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanDelete(Boolean value) {
        this.canDelete = value;
    }

    /**
     * Gets the value of the canArchive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanArchive() {
        return canArchive;
    }

    /**
     * Sets the value of the canArchive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanArchive(Boolean value) {
        this.canArchive = value;
    }

    /**
     * Gets the value of the canMove property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanMove() {
        return canMove;
    }

    /**
     * Sets the value of the canMove property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanMove(Boolean value) {
        this.canMove = value;
    }

}
