//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AbstractWidget complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AbstractWidget"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="if" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="if-module" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AbstractWidget")
@XmlSeeAlso({
    GanttView.Field.class,
    MenuItem.class,
    MenubarMenuItem.class,
    MenubarMenuDivider.class,
    MenubarMenu.class,
    SearchFilter.class,
    FormInclude.class,
    SimpleWidget.class
})
public abstract class AbstractWidget {

    @XmlAttribute(name = "if")
    protected String _if;
    @XmlAttribute(name = "if-module")
    protected String ifModule;

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIf(String value) {
        this._if = value;
    }

    /**
     * Gets the value of the ifModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfModule() {
        return ifModule;
    }

    /**
     * Sets the value of the ifModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfModule(String value) {
        this.ifModule = value;
    }

}
