//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseField"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://axelor.com/xml/ns/object-views}SimpleWidget"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="hilite" type="{http://axelor.com/xml/ns/object-views}Hilite" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="tooltip" type="{http://axelor.com/xml/ns/object-views}ToolTip" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://axelor.com/xml/ns/object-views}RelationalAttributes"/&gt;
 *       &lt;attGroup ref="{http://axelor.com/xml/ns/object-views}ExtraAttributes"/&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="placeholder" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="type" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="widget" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="selection" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="selection-in" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="requiredIf" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="validIf" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="onChange" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="min" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="max" type="{http://www.w3.org/2001/XMLSchema}decimal" /&gt;
 *       &lt;attribute name="pattern" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="fgColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="bgColor" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;anyAttribute processContents='skip'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseField", propOrder = {
    "hilite",
    "tooltip"
})
@XmlSeeAlso({
    PanelField.class,
    Field.class
})
public class BaseField
    extends SimpleWidget
{

    protected List<Hilite> hilite;
    protected ToolTip tooltip;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "placeholder")
    protected String placeholder;
    @XmlAttribute(name = "type")
    protected String type;
    @XmlAttribute(name = "widget")
    protected String widget;
    @XmlAttribute(name = "selection")
    protected String selection;
    @XmlAttribute(name = "selection-in")
    protected String selectionIn;
    @XmlAttribute(name = "required")
    protected Boolean required;
    @XmlAttribute(name = "requiredIf")
    protected String requiredIf;
    @XmlAttribute(name = "validIf")
    protected String validIf;
    @XmlAttribute(name = "onChange")
    protected String onChange;
    @XmlAttribute(name = "min")
    protected BigDecimal min;
    @XmlAttribute(name = "max")
    protected BigDecimal max;
    @XmlAttribute(name = "pattern")
    protected String pattern;
    @XmlAttribute(name = "fgColor")
    protected String fgColor;
    @XmlAttribute(name = "bgColor")
    protected String bgColor;
    @XmlAttribute(name = "target")
    @XmlSchemaType(name = "anySimpleType")
    protected String target;
    @XmlAttribute(name = "target-name")
    @XmlSchemaType(name = "anySimpleType")
    protected String targetName;
    @XmlAttribute(name = "domain")
    protected String domain;
    @XmlAttribute(name = "edit-window")
    protected String editWindow;
    @XmlAttribute(name = "form-view")
    protected String formView;
    @XmlAttribute(name = "grid-view")
    protected String gridView;
    @XmlAttribute(name = "summary-view")
    protected String summaryView;
    @XmlAttribute(name = "onSelect")
    protected String onSelect;
    @XmlAttribute(name = "canSuggest")
    protected Boolean canSuggest;
    @XmlAttribute(name = "canSelect")
    protected String canSelect;
    @XmlAttribute(name = "canNew")
    protected String canNew;
    @XmlAttribute(name = "canView")
    protected String canView;
    @XmlAttribute(name = "canEdit")
    protected String canEdit;
    @XmlAttribute(name = "canRemove")
    protected String canRemove;
    @XmlAttribute(name = "x-can-reload")
    protected Boolean xCanReload;
    @XmlAttribute(name = "x-call-onSave")
    protected Boolean xCallOnSave;
    @XmlAttribute(name = "x-search-limit")
    protected Integer xSearchLimit;
    @XmlAttribute(name = "x-color-field")
    protected String xColorField;
    @XmlAttribute(name = "x-popup-maximized")
    protected String xPopupMaximized;
    @XmlAttribute(name = "x-bind")
    protected String xBind;
    @XmlAttribute(name = "x-enum-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String xEnumType;
    @XmlAttribute(name = "x-related")
    protected String xRelated;
    @XmlAttribute(name = "x-create")
    protected String xCreate;
    @XmlAttribute(name = "x-icon")
    protected String xIcon;
    @XmlAttribute(name = "x-icon-hover")
    protected String xIconHover;
    @XmlAttribute(name = "x-icon-active")
    protected String xIconActive;
    @XmlAttribute(name = "x-exclusive")
    protected Boolean xExclusive;
    @XmlAttribute(name = "x-show-icons")
    protected String xShowIcons;
    @XmlAttribute(name = "x-show-bars")
    protected Boolean xShowBars;
    @XmlAttribute(name = "x-can-copy")
    protected Boolean xCanCopy;
    @XmlAttribute(name = "x-can-export")
    protected Boolean xCanExport;
    @XmlAttribute(name = "x-direction")
    protected String xDirection;
    @XmlAttribute(name = "x-code-syntax")
    protected String xCodeSyntax;
    @XmlAttribute(name = "x-code-theme")
    protected String xCodeTheme;
    @XmlAttribute(name = "x-lite")
    protected Boolean xLite;
    @XmlAttribute(name = "x-labels")
    protected Boolean xLabels;
    @XmlAttribute(name = "x-order")
    protected String xOrder;
    @XmlAttribute(name = "x-limit")
    protected Integer xLimit;
    @XmlAttribute(name = "x-precision")
    protected BigInteger xPrecision;
    @XmlAttribute(name = "x-scale")
    protected String xScale;
    @XmlAttribute(name = "x-currency")
    protected String xCurrency;
    @XmlAttribute(name = "x-true-text")
    protected String xTrueText;
    @XmlAttribute(name = "x-false-text")
    protected String xFalseText;
    @XmlAttribute(name = "x-big")
    protected Boolean xBig;
    @XmlAttribute(name = "x-seconds")
    protected Boolean xSeconds;
    @XmlAttribute(name = "x-accept")
    protected String xAccept;
    @XmlAttribute(name = "x-preview-style")
    protected String xPreviewStyle;
    @XmlAttribute(name = "x-initial-edit-type")
    protected String xInitialEditType;
    @XmlAttribute(name = "x-hide-mode-switch")
    protected Boolean xHideModeSwitch;

    /**
     * Gets the value of the hilite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hilite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHilite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Hilite }
     * 
     * 
     */
    public List<Hilite> getHilite() {
        if (hilite == null) {
            hilite = new ArrayList<Hilite>();
        }
        return this.hilite;
    }

    /**
     * Gets the value of the tooltip property.
     * 
     * @return
     *     possible object is
     *     {@link ToolTip }
     *     
     */
    public ToolTip getTooltip() {
        return tooltip;
    }

    /**
     * Sets the value of the tooltip property.
     * 
     * @param value
     *     allowed object is
     *     {@link ToolTip }
     *     
     */
    public void setTooltip(ToolTip value) {
        this.tooltip = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the placeholder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlaceholder() {
        return placeholder;
    }

    /**
     * Sets the value of the placeholder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlaceholder(String value) {
        this.placeholder = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the widget property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidget() {
        return widget;
    }

    /**
     * Sets the value of the widget property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidget(String value) {
        this.widget = value;
    }

    /**
     * Gets the value of the selection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelection() {
        return selection;
    }

    /**
     * Sets the value of the selection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelection(String value) {
        this.selection = value;
    }

    /**
     * Gets the value of the selectionIn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSelectionIn() {
        return selectionIn;
    }

    /**
     * Sets the value of the selectionIn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSelectionIn(String value) {
        this.selectionIn = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the requiredIf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequiredIf() {
        return requiredIf;
    }

    /**
     * Sets the value of the requiredIf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequiredIf(String value) {
        this.requiredIf = value;
    }

    /**
     * Gets the value of the validIf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidIf() {
        return validIf;
    }

    /**
     * Sets the value of the validIf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidIf(String value) {
        this.validIf = value;
    }

    /**
     * Gets the value of the onChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnChange() {
        return onChange;
    }

    /**
     * Sets the value of the onChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnChange(String value) {
        this.onChange = value;
    }

    /**
     * Gets the value of the min property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMin() {
        return min;
    }

    /**
     * Sets the value of the min property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMin(BigDecimal value) {
        this.min = value;
    }

    /**
     * Gets the value of the max property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMax() {
        return max;
    }

    /**
     * Sets the value of the max property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMax(BigDecimal value) {
        this.max = value;
    }

    /**
     * Gets the value of the pattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPattern() {
        return pattern;
    }

    /**
     * Sets the value of the pattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPattern(String value) {
        this.pattern = value;
    }

    /**
     * Gets the value of the fgColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFgColor() {
        return fgColor;
    }

    /**
     * Sets the value of the fgColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFgColor(String value) {
        this.fgColor = value;
    }

    /**
     * Gets the value of the bgColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBgColor() {
        return bgColor;
    }

    /**
     * Sets the value of the bgColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBgColor(String value) {
        this.bgColor = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the targetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * Sets the value of the targetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetName(String value) {
        this.targetName = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomain(String value) {
        this.domain = value;
    }

    /**
     * Gets the value of the editWindow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditWindow() {
        return editWindow;
    }

    /**
     * Sets the value of the editWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditWindow(String value) {
        this.editWindow = value;
    }

    /**
     * Gets the value of the formView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormView() {
        return formView;
    }

    /**
     * Sets the value of the formView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormView(String value) {
        this.formView = value;
    }

    /**
     * Gets the value of the gridView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridView() {
        return gridView;
    }

    /**
     * Sets the value of the gridView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridView(String value) {
        this.gridView = value;
    }

    /**
     * Gets the value of the summaryView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryView() {
        return summaryView;
    }

    /**
     * Sets the value of the summaryView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryView(String value) {
        this.summaryView = value;
    }

    /**
     * Gets the value of the onSelect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnSelect() {
        return onSelect;
    }

    /**
     * Sets the value of the onSelect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnSelect(String value) {
        this.onSelect = value;
    }

    /**
     * Gets the value of the canSuggest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCanSuggest() {
        if (canSuggest == null) {
            return true;
        } else {
            return canSuggest;
        }
    }

    /**
     * Sets the value of the canSuggest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanSuggest(Boolean value) {
        this.canSuggest = value;
    }

    /**
     * Gets the value of the canSelect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanSelect() {
        return canSelect;
    }

    /**
     * Sets the value of the canSelect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanSelect(String value) {
        this.canSelect = value;
    }

    /**
     * Gets the value of the canNew property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanNew() {
        return canNew;
    }

    /**
     * Sets the value of the canNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanNew(String value) {
        this.canNew = value;
    }

    /**
     * Gets the value of the canView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanView() {
        return canView;
    }

    /**
     * Sets the value of the canView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanView(String value) {
        this.canView = value;
    }

    /**
     * Gets the value of the canEdit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanEdit() {
        return canEdit;
    }

    /**
     * Sets the value of the canEdit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanEdit(String value) {
        this.canEdit = value;
    }

    /**
     * Gets the value of the canRemove property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanRemove() {
        return canRemove;
    }

    /**
     * Sets the value of the canRemove property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanRemove(String value) {
        this.canRemove = value;
    }

    /**
     * Gets the value of the xCanReload property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXCanReload() {
        return xCanReload;
    }

    /**
     * Sets the value of the xCanReload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXCanReload(Boolean value) {
        this.xCanReload = value;
    }

    /**
     * Gets the value of the xCallOnSave property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXCallOnSave() {
        return xCallOnSave;
    }

    /**
     * Sets the value of the xCallOnSave property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXCallOnSave(Boolean value) {
        this.xCallOnSave = value;
    }

    /**
     * Gets the value of the xSearchLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getXSearchLimit() {
        return xSearchLimit;
    }

    /**
     * Sets the value of the xSearchLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setXSearchLimit(Integer value) {
        this.xSearchLimit = value;
    }

    /**
     * Gets the value of the xColorField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXColorField() {
        return xColorField;
    }

    /**
     * Sets the value of the xColorField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXColorField(String value) {
        this.xColorField = value;
    }

    /**
     * Gets the value of the xPopupMaximized property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPopupMaximized() {
        return xPopupMaximized;
    }

    /**
     * Sets the value of the xPopupMaximized property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPopupMaximized(String value) {
        this.xPopupMaximized = value;
    }

    /**
     * Gets the value of the xBind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXBind() {
        return xBind;
    }

    /**
     * Sets the value of the xBind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXBind(String value) {
        this.xBind = value;
    }

    /**
     * Gets the value of the xEnumType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXEnumType() {
        return xEnumType;
    }

    /**
     * Sets the value of the xEnumType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXEnumType(String value) {
        this.xEnumType = value;
    }

    /**
     * Gets the value of the xRelated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXRelated() {
        return xRelated;
    }

    /**
     * Sets the value of the xRelated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXRelated(String value) {
        this.xRelated = value;
    }

    /**
     * Gets the value of the xCreate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCreate() {
        return xCreate;
    }

    /**
     * Sets the value of the xCreate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCreate(String value) {
        this.xCreate = value;
    }

    /**
     * Gets the value of the xIcon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXIcon() {
        return xIcon;
    }

    /**
     * Sets the value of the xIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXIcon(String value) {
        this.xIcon = value;
    }

    /**
     * Gets the value of the xIconHover property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXIconHover() {
        return xIconHover;
    }

    /**
     * Sets the value of the xIconHover property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXIconHover(String value) {
        this.xIconHover = value;
    }

    /**
     * Gets the value of the xIconActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXIconActive() {
        return xIconActive;
    }

    /**
     * Sets the value of the xIconActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXIconActive(String value) {
        this.xIconActive = value;
    }

    /**
     * Gets the value of the xExclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXExclusive() {
        return xExclusive;
    }

    /**
     * Sets the value of the xExclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXExclusive(Boolean value) {
        this.xExclusive = value;
    }

    /**
     * Gets the value of the xShowIcons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXShowIcons() {
        return xShowIcons;
    }

    /**
     * Sets the value of the xShowIcons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXShowIcons(String value) {
        this.xShowIcons = value;
    }

    /**
     * Gets the value of the xShowBars property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXShowBars() {
        return xShowBars;
    }

    /**
     * Sets the value of the xShowBars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXShowBars(Boolean value) {
        this.xShowBars = value;
    }

    /**
     * Gets the value of the xCanCopy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXCanCopy() {
        return xCanCopy;
    }

    /**
     * Sets the value of the xCanCopy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXCanCopy(Boolean value) {
        this.xCanCopy = value;
    }

    /**
     * Gets the value of the xCanExport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXCanExport() {
        return xCanExport;
    }

    /**
     * Sets the value of the xCanExport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXCanExport(Boolean value) {
        this.xCanExport = value;
    }

    /**
     * Gets the value of the xDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDirection() {
        return xDirection;
    }

    /**
     * Sets the value of the xDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDirection(String value) {
        this.xDirection = value;
    }

    /**
     * Gets the value of the xCodeSyntax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCodeSyntax() {
        return xCodeSyntax;
    }

    /**
     * Sets the value of the xCodeSyntax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCodeSyntax(String value) {
        this.xCodeSyntax = value;
    }

    /**
     * Gets the value of the xCodeTheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCodeTheme() {
        return xCodeTheme;
    }

    /**
     * Sets the value of the xCodeTheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCodeTheme(String value) {
        this.xCodeTheme = value;
    }

    /**
     * Gets the value of the xLite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXLite() {
        return xLite;
    }

    /**
     * Sets the value of the xLite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXLite(Boolean value) {
        this.xLite = value;
    }

    /**
     * Gets the value of the xLabels property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXLabels() {
        return xLabels;
    }

    /**
     * Sets the value of the xLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXLabels(Boolean value) {
        this.xLabels = value;
    }

    /**
     * Gets the value of the xOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXOrder() {
        return xOrder;
    }

    /**
     * Sets the value of the xOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXOrder(String value) {
        this.xOrder = value;
    }

    /**
     * Gets the value of the xLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getXLimit() {
        return xLimit;
    }

    /**
     * Sets the value of the xLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setXLimit(Integer value) {
        this.xLimit = value;
    }

    /**
     * Gets the value of the xPrecision property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXPrecision() {
        return xPrecision;
    }

    /**
     * Sets the value of the xPrecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXPrecision(BigInteger value) {
        this.xPrecision = value;
    }

    /**
     * Gets the value of the xScale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXScale() {
        return xScale;
    }

    /**
     * Sets the value of the xScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXScale(String value) {
        this.xScale = value;
    }

    /**
     * Gets the value of the xCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCurrency() {
        return xCurrency;
    }

    /**
     * Sets the value of the xCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCurrency(String value) {
        this.xCurrency = value;
    }

    /**
     * Gets the value of the xTrueText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXTrueText() {
        return xTrueText;
    }

    /**
     * Sets the value of the xTrueText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXTrueText(String value) {
        this.xTrueText = value;
    }

    /**
     * Gets the value of the xFalseText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXFalseText() {
        return xFalseText;
    }

    /**
     * Sets the value of the xFalseText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXFalseText(String value) {
        this.xFalseText = value;
    }

    /**
     * Gets the value of the xBig property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXBig() {
        return xBig;
    }

    /**
     * Sets the value of the xBig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXBig(Boolean value) {
        this.xBig = value;
    }

    /**
     * Gets the value of the xSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXSeconds() {
        return xSeconds;
    }

    /**
     * Sets the value of the xSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXSeconds(Boolean value) {
        this.xSeconds = value;
    }

    /**
     * Gets the value of the xAccept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXAccept() {
        return xAccept;
    }

    /**
     * Sets the value of the xAccept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXAccept(String value) {
        this.xAccept = value;
    }

    /**
     * Gets the value of the xPreviewStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPreviewStyle() {
        if (xPreviewStyle == null) {
            return "tab";
        } else {
            return xPreviewStyle;
        }
    }

    /**
     * Sets the value of the xPreviewStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPreviewStyle(String value) {
        this.xPreviewStyle = value;
    }

    /**
     * Gets the value of the xInitialEditType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXInitialEditType() {
        if (xInitialEditType == null) {
            return "markdown";
        } else {
            return xInitialEditType;
        }
    }

    /**
     * Sets the value of the xInitialEditType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXInitialEditType(String value) {
        this.xInitialEditType = value;
    }

    /**
     * Gets the value of the xHideModeSwitch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isXHideModeSwitch() {
        if (xHideModeSwitch == null) {
            return false;
        } else {
            return xHideModeSwitch;
        }
    }

    /**
     * Sets the value of the xHideModeSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXHideModeSwitch(Boolean value) {
        this.xHideModeSwitch = value;
    }

}
