//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardEditWindow.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CardEditWindow"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="self"/&gt;
 *     &lt;enumeration value="popup"/&gt;
 *     &lt;enumeration value="popup-new"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CardEditWindow")
@XmlEnum
public enum CardEditWindow {


    /**
     * Show editor in same tab.
     * 
     */
    @XmlEnumValue("self")
    SELF("self"),

    /**
     * Show popup editor
     * 
     */
    @XmlEnumValue("popup")
    POPUP("popup"),

    /**
     * Show popup editor when creating new record.
     * 
     */
    @XmlEnumValue("popup-new")
    POPUP_NEW("popup-new");
    private final String value;

    CardEditWindow(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CardEditWindow fromValue(String v) {
        for (CardEditWindow c: CardEditWindow.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
