//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardsView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardsView"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://axelor.com/xml/ns/object-views}SimpleView"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="toolbar" type="{http://axelor.com/xml/ns/object-views}Toolbar" minOccurs="0"/&gt;
 *         &lt;element name="menubar" type="{http://axelor.com/xml/ns/object-views}Menubar" minOccurs="0"/&gt;
 *         &lt;element name="field" type="{http://axelor.com/xml/ns/object-views}CardField" maxOccurs="unbounded"/&gt;
 *         &lt;element name="hilite" type="{http://axelor.com/xml/ns/object-views}CardStyle" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="template" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://axelor.com/xml/ns/object-views}AdvanceSearchAttributes"/&gt;
 *       &lt;attribute name="model" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="orderBy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="canNew" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="canEdit" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="canDelete" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="edit-window" type="{http://axelor.com/xml/ns/object-views}CardEditWindow" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardsView", propOrder = {
    "toolbar",
    "menubar",
    "field",
    "hilite",
    "template"
})
@XmlSeeAlso({
    KanbanView.class
})
public class CardsView
    extends SimpleView
{

    protected Toolbar toolbar;
    protected Menubar menubar;
    @XmlElement(required = true)
    protected List<CardField> field;
    protected List<CardStyle> hilite;
    @XmlElement(required = true)
    protected String template;
    @XmlAttribute(name = "model", required = true)
    protected String model;
    @XmlAttribute(name = "orderBy")
    protected String orderBy;
    @XmlAttribute(name = "canNew")
    protected Boolean canNew;
    @XmlAttribute(name = "canEdit")
    protected Boolean canEdit;
    @XmlAttribute(name = "canDelete")
    protected Boolean canDelete;
    @XmlAttribute(name = "edit-window")
    protected CardEditWindow editWindow;
    @XmlAttribute(name = "customSearch")
    protected Boolean customSearch;
    @XmlAttribute(name = "freeSearch")
    protected String freeSearch;

    /**
     * Gets the value of the toolbar property.
     * 
     * @return
     *     possible object is
     *     {@link Toolbar }
     *     
     */
    public Toolbar getToolbar() {
        return toolbar;
    }

    /**
     * Sets the value of the toolbar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Toolbar }
     *     
     */
    public void setToolbar(Toolbar value) {
        this.toolbar = value;
    }

    /**
     * Gets the value of the menubar property.
     * 
     * @return
     *     possible object is
     *     {@link Menubar }
     *     
     */
    public Menubar getMenubar() {
        return menubar;
    }

    /**
     * Sets the value of the menubar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Menubar }
     *     
     */
    public void setMenubar(Menubar value) {
        this.menubar = value;
    }

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CardField }
     * 
     * 
     */
    public List<CardField> getField() {
        if (field == null) {
            field = new ArrayList<CardField>();
        }
        return this.field;
    }

    /**
     * Gets the value of the hilite property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hilite property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHilite().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CardStyle }
     * 
     * 
     */
    public List<CardStyle> getHilite() {
        if (hilite == null) {
            hilite = new ArrayList<CardStyle>();
        }
        return this.hilite;
    }

    /**
     * Gets the value of the template property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTemplate() {
        return template;
    }

    /**
     * Sets the value of the template property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTemplate(String value) {
        this.template = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the orderBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderBy() {
        return orderBy;
    }

    /**
     * Sets the value of the orderBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderBy(String value) {
        this.orderBy = value;
    }

    /**
     * Gets the value of the canNew property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanNew() {
        return canNew;
    }

    /**
     * Sets the value of the canNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanNew(Boolean value) {
        this.canNew = value;
    }

    /**
     * Gets the value of the canEdit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanEdit() {
        return canEdit;
    }

    /**
     * Sets the value of the canEdit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanEdit(Boolean value) {
        this.canEdit = value;
    }

    /**
     * Gets the value of the canDelete property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanDelete() {
        return canDelete;
    }

    /**
     * Sets the value of the canDelete property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanDelete(Boolean value) {
        this.canDelete = value;
    }

    /**
     * Gets the value of the editWindow property.
     * 
     * @return
     *     possible object is
     *     {@link CardEditWindow }
     *     
     */
    public CardEditWindow getEditWindow() {
        return editWindow;
    }

    /**
     * Sets the value of the editWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link CardEditWindow }
     *     
     */
    public void setEditWindow(CardEditWindow value) {
        this.editWindow = value;
    }

    /**
     * Gets the value of the customSearch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCustomSearch() {
        return customSearch;
    }

    /**
     * Sets the value of the customSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCustomSearch(Boolean value) {
        this.customSearch = value;
    }

    /**
     * Gets the value of the freeSearch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreeSearch() {
        return freeSearch;
    }

    /**
     * Sets the value of the freeSearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreeSearch(String value) {
        this.freeSearch = value;
    }

}
