//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ColorNameStyle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ColorNameStyle"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="red"/&gt;
 *     &lt;enumeration value="pink"/&gt;
 *     &lt;enumeration value="purple"/&gt;
 *     &lt;enumeration value="deeppurple"/&gt;
 *     &lt;enumeration value="indigo"/&gt;
 *     &lt;enumeration value="blue"/&gt;
 *     &lt;enumeration value="lightblue"/&gt;
 *     &lt;enumeration value="cyan"/&gt;
 *     &lt;enumeration value="teal"/&gt;
 *     &lt;enumeration value="green"/&gt;
 *     &lt;enumeration value="lightgreen"/&gt;
 *     &lt;enumeration value="lime"/&gt;
 *     &lt;enumeration value="yellow"/&gt;
 *     &lt;enumeration value="amber"/&gt;
 *     &lt;enumeration value="orange"/&gt;
 *     &lt;enumeration value="deeporange"/&gt;
 *     &lt;enumeration value="brown"/&gt;
 *     &lt;enumeration value="grey"/&gt;
 *     &lt;enumeration value="bluegrey"/&gt;
 *     &lt;enumeration value="black"/&gt;
 *     &lt;enumeration value="white"/&gt;
 *     &lt;enumeration value="olive"/&gt;
 *     &lt;enumeration value="violet"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ColorNameStyle")
@XmlEnum
public enum ColorNameStyle {

    @XmlEnumValue("red")
    RED("red"),
    @XmlEnumValue("pink")
    PINK("pink"),
    @XmlEnumValue("purple")
    PURPLE("purple"),
    @XmlEnumValue("deeppurple")
    DEEPPURPLE("deeppurple"),
    @XmlEnumValue("indigo")
    INDIGO("indigo"),
    @XmlEnumValue("blue")
    BLUE("blue"),
    @XmlEnumValue("lightblue")
    LIGHTBLUE("lightblue"),
    @XmlEnumValue("cyan")
    CYAN("cyan"),
    @XmlEnumValue("teal")
    TEAL("teal"),
    @XmlEnumValue("green")
    GREEN("green"),
    @XmlEnumValue("lightgreen")
    LIGHTGREEN("lightgreen"),
    @XmlEnumValue("lime")
    LIME("lime"),
    @XmlEnumValue("yellow")
    YELLOW("yellow"),
    @XmlEnumValue("amber")
    AMBER("amber"),
    @XmlEnumValue("orange")
    ORANGE("orange"),
    @XmlEnumValue("deeporange")
    DEEPORANGE("deeporange"),
    @XmlEnumValue("brown")
    BROWN("brown"),
    @XmlEnumValue("grey")
    GREY("grey"),
    @XmlEnumValue("bluegrey")
    BLUEGREY("bluegrey"),
    @XmlEnumValue("black")
    BLACK("black"),
    @XmlEnumValue("white")
    WHITE("white"),
    @XmlEnumValue("olive")
    OLIVE("olive"),
    @XmlEnumValue("violet")
    VIOLET("violet");
    private final String value;

    ColorNameStyle(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ColorNameStyle fromValue(String v) {
        for (ColorNameStyle c: ColorNameStyle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
