//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExtendForm complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExtendForm"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="attribute" type="{http://axelor.com/xml/ns/object-views}ExtendAttribute"/&gt;
 *         &lt;element name="insert"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded"&gt;
 *                   &lt;group ref="{http://axelor.com/xml/ns/object-views}ExtendFormItems"/&gt;
 *                 &lt;/choice&gt;
 *                 &lt;attribute name="position" use="required" type="{http://axelor.com/xml/ns/object-views}Position" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="replace"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *                   &lt;group ref="{http://axelor.com/xml/ns/object-views}ExtendFormItems"/&gt;
 *                 &lt;/choice&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="move"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="position" use="required" type="{http://axelor.com/xml/ns/object-views}Position" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="target" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="if-feature" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="if-module" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExtendForm", propOrder = {
    "attributeOrInsertOrReplace"
})
public class ExtendForm {

    @XmlElements({
        @XmlElement(name = "attribute", type = ExtendAttribute.class),
        @XmlElement(name = "insert", type = Insert.class),
        @XmlElement(name = "replace", type = Replace.class),
        @XmlElement(name = "move", type = Move.class)
    })
    protected List<Object> attributeOrInsertOrReplace;
    @XmlAttribute(name = "target", required = true)
    protected String target;
    @XmlAttribute(name = "if-feature")
    protected String ifFeature;
    @XmlAttribute(name = "if-module")
    protected String ifModule;

    /**
     * Gets the value of the attributeOrInsertOrReplace property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeOrInsertOrReplace property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeOrInsertOrReplace().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExtendAttribute }
     * {@link Insert }
     * {@link Replace }
     * {@link Move }
     * 
     * 
     */
    public List<Object> getAttributeOrInsertOrReplace() {
        if (attributeOrInsertOrReplace == null) {
            attributeOrInsertOrReplace = new ArrayList<Object>();
        }
        return this.attributeOrInsertOrReplace;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the ifFeature property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfFeature() {
        return ifFeature;
    }

    /**
     * Sets the value of the ifFeature property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfFeature(String value) {
        this.ifFeature = value;
    }

    /**
     * Gets the value of the ifModule property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIfModule() {
        return ifModule;
    }

    /**
     * Sets the value of the ifModule property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIfModule(String value) {
        this.ifModule = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice maxOccurs="unbounded"&gt;
     *         &lt;group ref="{http://axelor.com/xml/ns/object-views}ExtendFormItems"/&gt;
     *       &lt;/choice&gt;
     *       &lt;attribute name="position" use="required" type="{http://axelor.com/xml/ns/object-views}Position" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldOrLabelOrHelp"
    })
    public static class Insert {

        @XmlElementRefs({
            @XmlElementRef(name = "field", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "label", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "help", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "static", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "spacer", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "separator", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "button", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "button-group", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-related", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-dashlet", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-include", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "toolbar", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "menubar", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "menu", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "item", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "divider", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "tooltip", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "viewer", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "editor", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-stack", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-tabs", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-mail", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<?>> fieldOrLabelOrHelp;
        @XmlAttribute(name = "position", required = true)
        protected Position position;

        /**
         * Gets the value of the fieldOrLabelOrHelp property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fieldOrLabelOrHelp property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFieldOrLabelOrHelp().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link PanelField }{@code >}
         * {@link JAXBElement }{@code <}{@link Label }{@code >}
         * {@link JAXBElement }{@code <}{@link Help }{@code >}
         * {@link JAXBElement }{@code <}{@link Static }{@code >}
         * {@link JAXBElement }{@code <}{@link Spacer }{@code >}
         * {@link JAXBElement }{@code <}{@link Separator }{@code >}
         * {@link JAXBElement }{@code <}{@link Button }{@code >}
         * {@link JAXBElement }{@code <}{@link Replace.ButtonGroup }{@code >}
         * {@link JAXBElement }{@code <}{@link Replace.Panel }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelRelated }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelDashlet }{@code >}
         * {@link JAXBElement }{@code <}{@link FormInclude }{@code >}
         * {@link JAXBElement }{@code <}{@link Toolbar }{@code >}
         * {@link JAXBElement }{@code <}{@link Menubar }{@code >}
         * {@link JAXBElement }{@code <}{@link MenubarMenu }{@code >}
         * {@link JAXBElement }{@code <}{@link MenubarMenuItem }{@code >}
         * {@link JAXBElement }{@code <}{@link MenubarMenuDivider }{@code >}
         * {@link JAXBElement }{@code <}{@link ToolTip }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelViewer }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelEditor }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelTabs }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelTabs }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelMail }{@code >}
         * 
         * 
         */
        public List<JAXBElement<?>> getFieldOrLabelOrHelp() {
            if (fieldOrLabelOrHelp == null) {
                fieldOrLabelOrHelp = new ArrayList<JAXBElement<?>>();
            }
            return this.fieldOrLabelOrHelp;
        }

        /**
         * Gets the value of the position property.
         * 
         * @return
         *     possible object is
         *     {@link Position }
         *     
         */
        public Position getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         * 
         * @param value
         *     allowed object is
         *     {@link Position }
         *     
         */
        public void setPosition(Position value) {
            this.position = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="source" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="position" use="required" type="{http://axelor.com/xml/ns/object-views}Position" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Move {

        @XmlAttribute(name = "source", required = true)
        protected String source;
        @XmlAttribute(name = "position", required = true)
        protected Position position;

        /**
         * Gets the value of the source property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSource() {
            return source;
        }

        /**
         * Sets the value of the source property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSource(String value) {
            this.source = value;
        }

        /**
         * Gets the value of the position property.
         * 
         * @return
         *     possible object is
         *     {@link Position }
         *     
         */
        public Position getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         * 
         * @param value
         *     allowed object is
         *     {@link Position }
         *     
         */
        public void setPosition(Position value) {
            this.position = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
     *         &lt;group ref="{http://axelor.com/xml/ns/object-views}ExtendFormItems"/&gt;
     *       &lt;/choice&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "fieldOrLabelOrHelp"
    })
    public static class Replace {

        @XmlElementRefs({
            @XmlElementRef(name = "field", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "label", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "help", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "static", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "spacer", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "separator", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "button", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "button-group", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-related", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-dashlet", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-include", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "toolbar", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "menubar", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "menu", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "item", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "divider", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "tooltip", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "viewer", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "editor", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-stack", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-tabs", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "panel-mail", namespace = "http://axelor.com/xml/ns/object-views", type = JAXBElement.class, required = false)
        })
        protected List<JAXBElement<?>> fieldOrLabelOrHelp;

        /**
         * Gets the value of the fieldOrLabelOrHelp property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the fieldOrLabelOrHelp property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getFieldOrLabelOrHelp().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link PanelField }{@code >}
         * {@link JAXBElement }{@code <}{@link Label }{@code >}
         * {@link JAXBElement }{@code <}{@link Help }{@code >}
         * {@link JAXBElement }{@code <}{@link Static }{@code >}
         * {@link JAXBElement }{@code <}{@link Spacer }{@code >}
         * {@link JAXBElement }{@code <}{@link Separator }{@code >}
         * {@link JAXBElement }{@code <}{@link Button }{@code >}
         * {@link JAXBElement }{@code <}{@link ButtonGroup }{@code >}
         * {@link JAXBElement }{@code <}{@link Panel }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelRelated }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelDashlet }{@code >}
         * {@link JAXBElement }{@code <}{@link FormInclude }{@code >}
         * {@link JAXBElement }{@code <}{@link Toolbar }{@code >}
         * {@link JAXBElement }{@code <}{@link Menubar }{@code >}
         * {@link JAXBElement }{@code <}{@link MenubarMenu }{@code >}
         * {@link JAXBElement }{@code <}{@link MenubarMenuItem }{@code >}
         * {@link JAXBElement }{@code <}{@link MenubarMenuDivider }{@code >}
         * {@link JAXBElement }{@code <}{@link ToolTip }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelViewer }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelEditor }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelTabs }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelTabs }{@code >}
         * {@link JAXBElement }{@code <}{@link PanelMail }{@code >}
         * 
         * 
         */
        public List<JAXBElement<?>> getFieldOrLabelOrHelp() {
            if (fieldOrLabelOrHelp == null) {
                fieldOrLabelOrHelp = new ArrayList<JAXBElement<?>>();
            }
            return this.fieldOrLabelOrHelp;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;extension base="{http://axelor.com/xml/ns/object-views}AbstractContainer"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="button" type="{http://axelor.com/xml/ns/object-views}Button" maxOccurs="unbounded"/&gt;
         *       &lt;/sequence&gt;
         *       &lt;anyAttribute processContents='skip'/&gt;
         *     &lt;/extension&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "button"
        })
        public static class ButtonGroup
            extends AbstractContainer
        {

            @XmlElement(required = true)
            protected List<Button> button;

            /**
             * Gets the value of the button property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the button property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getButton().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link Button }
             * 
             * 
             */
            public List<Button> getButton() {
                if (button == null) {
                    button = new ArrayList<Button>();
                }
                return this.button;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;extension base="{http://axelor.com/xml/ns/object-views}AbstractPanel"&gt;
         *       &lt;group ref="{http://axelor.com/xml/ns/object-views}PanelItems" maxOccurs="unbounded"/&gt;
         *       &lt;anyAttribute processContents='skip'/&gt;
         *     &lt;/extension&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "panelItems"
        })
        public static class Panel
            extends AbstractPanel
        {

            @XmlElements({
                @XmlElement(name = "field", type = PanelField.class),
                @XmlElement(name = "label", type = Label.class),
                @XmlElement(name = "help", type = Help.class),
                @XmlElement(name = "static", type = Static.class),
                @XmlElement(name = "spacer", type = Spacer.class),
                @XmlElement(name = "separator", type = Separator.class),
                @XmlElement(name = "button", type = Button.class),
                @XmlElement(name = "button-group", type = ButtonGroup.class),
                @XmlElement(name = "panel", type = Panel.class),
                @XmlElement(name = "panel-related", type = PanelRelated.class),
                @XmlElement(name = "panel-dashlet", type = PanelDashlet.class),
                @XmlElement(name = "panel-include", type = FormInclude.class)
            })
            protected List<AbstractWidget> panelItems;

            /**
             * Gets the value of the panelItems property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the panelItems property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getPanelItems().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link PanelField }
             * {@link Label }
             * {@link Help }
             * {@link Static }
             * {@link Spacer }
             * {@link Separator }
             * {@link Button }
             * {@link ButtonGroup }
             * {@link Panel }
             * {@link PanelRelated }
             * {@link PanelDashlet }
             * {@link FormInclude }
             * 
             * 
             */
            public List<AbstractWidget> getPanelItems() {
                if (panelItems == null) {
                    panelItems = new ArrayList<AbstractWidget>();
                }
                return this.panelItems;
            }

        }

    }

}
