//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GanttView complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GanttView"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://axelor.com/xml/ns/object-views}AbstractView"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="field" maxOccurs="3"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://axelor.com/xml/ns/object-views}AbstractWidget"&gt;
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://axelor.com/xml/ns/object-views}ObjectViewAttributes"/&gt;
 *       &lt;attribute name="taskStart" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="taskDuration" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="taskEnd" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="taskParent" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="taskProgress" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="taskSequence" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="taskUser" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="mode" default="month"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="year"/&gt;
 *             &lt;enumeration value="month"/&gt;
 *             &lt;enumeration value="week"/&gt;
 *             &lt;enumeration value="day"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="x-finish-to-start" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="x-start-to-start" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="x-finish-to-finish" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="x-start-to-finish" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GanttView", propOrder = {
    "field"
})
public class GanttView
    extends AbstractView
{

    @XmlElement(required = true)
    protected List<Field> field;
    @XmlAttribute(name = "taskStart", required = true)
    protected String taskStart;
    @XmlAttribute(name = "taskDuration")
    protected String taskDuration;
    @XmlAttribute(name = "taskEnd")
    protected String taskEnd;
    @XmlAttribute(name = "taskParent")
    protected String taskParent;
    @XmlAttribute(name = "taskProgress")
    protected String taskProgress;
    @XmlAttribute(name = "taskSequence")
    protected String taskSequence;
    @XmlAttribute(name = "taskUser")
    protected String taskUser;
    @XmlAttribute(name = "mode")
    protected String mode;
    @XmlAttribute(name = "x-finish-to-start")
    protected String xFinishToStart;
    @XmlAttribute(name = "x-start-to-start")
    protected String xStartToStart;
    @XmlAttribute(name = "x-finish-to-finish")
    protected String xFinishToFinish;
    @XmlAttribute(name = "x-start-to-finish")
    protected String xStartToFinish;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "model", required = true)
    protected String model;
    @XmlAttribute(name = "editable")
    protected Boolean editable;

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getField() {
        if (field == null) {
            field = new ArrayList<Field>();
        }
        return this.field;
    }

    /**
     * Gets the value of the taskStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskStart() {
        return taskStart;
    }

    /**
     * Sets the value of the taskStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskStart(String value) {
        this.taskStart = value;
    }

    /**
     * Gets the value of the taskDuration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskDuration() {
        return taskDuration;
    }

    /**
     * Sets the value of the taskDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskDuration(String value) {
        this.taskDuration = value;
    }

    /**
     * Gets the value of the taskEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskEnd() {
        return taskEnd;
    }

    /**
     * Sets the value of the taskEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskEnd(String value) {
        this.taskEnd = value;
    }

    /**
     * Gets the value of the taskParent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskParent() {
        return taskParent;
    }

    /**
     * Sets the value of the taskParent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskParent(String value) {
        this.taskParent = value;
    }

    /**
     * Gets the value of the taskProgress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskProgress() {
        return taskProgress;
    }

    /**
     * Sets the value of the taskProgress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskProgress(String value) {
        this.taskProgress = value;
    }

    /**
     * Gets the value of the taskSequence property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskSequence() {
        return taskSequence;
    }

    /**
     * Sets the value of the taskSequence property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskSequence(String value) {
        this.taskSequence = value;
    }

    /**
     * Gets the value of the taskUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaskUser() {
        return taskUser;
    }

    /**
     * Sets the value of the taskUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaskUser(String value) {
        this.taskUser = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMode() {
        if (mode == null) {
            return "month";
        } else {
            return mode;
        }
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMode(String value) {
        this.mode = value;
    }

    /**
     * Gets the value of the xFinishToStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXFinishToStart() {
        return xFinishToStart;
    }

    /**
     * Sets the value of the xFinishToStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXFinishToStart(String value) {
        this.xFinishToStart = value;
    }

    /**
     * Gets the value of the xStartToStart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXStartToStart() {
        return xStartToStart;
    }

    /**
     * Sets the value of the xStartToStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXStartToStart(String value) {
        this.xStartToStart = value;
    }

    /**
     * Gets the value of the xFinishToFinish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXFinishToFinish() {
        return xFinishToFinish;
    }

    /**
     * Sets the value of the xFinishToFinish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXFinishToFinish(String value) {
        this.xFinishToFinish = value;
    }

    /**
     * Gets the value of the xStartToFinish property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXStartToFinish() {
        return xStartToFinish;
    }

    /**
     * Sets the value of the xStartToFinish property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXStartToFinish(String value) {
        this.xStartToFinish = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the editable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEditable() {
        return editable;
    }

    /**
     * Sets the value of the editable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditable(Boolean value) {
        this.editable = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://axelor.com/xml/ns/object-views}AbstractWidget"&gt;
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Field
        extends AbstractWidget
    {

        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "title")
        protected String title;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

    }

}
