//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MenubarMenuItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MenubarMenuItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://axelor.com/xml/ns/object-views}AbstractWidget"&gt;
 *       &lt;attribute name="title" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="action" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="prompt" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="depends" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="showIf" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="hideIf" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="readonlyIf" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MenubarMenuItem")
public class MenubarMenuItem
    extends AbstractWidget
{

    @XmlAttribute(name = "title", required = true)
    protected String title;
    @XmlAttribute(name = "action", required = true)
    protected String action;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "prompt")
    protected String prompt;
    @XmlAttribute(name = "depends")
    protected String depends;
    @XmlAttribute(name = "showIf")
    protected String showIf;
    @XmlAttribute(name = "hideIf")
    protected String hideIf;
    @XmlAttribute(name = "readonlyIf")
    protected String readonlyIf;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAction(String value) {
        this.action = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the prompt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrompt() {
        return prompt;
    }

    /**
     * Sets the value of the prompt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrompt(String value) {
        this.prompt = value;
    }

    /**
     * Gets the value of the depends property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepends() {
        return depends;
    }

    /**
     * Sets the value of the depends property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepends(String value) {
        this.depends = value;
    }

    /**
     * Gets the value of the showIf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getShowIf() {
        return showIf;
    }

    /**
     * Sets the value of the showIf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setShowIf(String value) {
        this.showIf = value;
    }

    /**
     * Gets the value of the hideIf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHideIf() {
        return hideIf;
    }

    /**
     * Sets the value of the hideIf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHideIf(String value) {
        this.hideIf = value;
    }

    /**
     * Gets the value of the readonlyIf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReadonlyIf() {
        return readonlyIf;
    }

    /**
     * Sets the value of the readonlyIf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReadonlyIf(String value) {
        this.readonlyIf = value;
    }

}
