//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PanelField complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PanelField"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://axelor.com/xml/ns/object-views}BaseField"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="viewer" type="{http://axelor.com/xml/ns/object-views}PanelViewer" minOccurs="0"/&gt;
 *         &lt;element name="editor" type="{http://axelor.com/xml/ns/object-views}PanelEditor" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='skip'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MyElement", propOrder = {
    "viewer",
    "editor"
})
public class MyElement
    extends BaseField
{

    protected PanelViewer viewer;
    protected PanelEditor editor;

    /**
     * Gets the value of the viewer property.
     * 
     * @return
     *     possible object is
     *     {@link PanelViewer }
     *     
     */
    public PanelViewer getViewer() {
        return viewer;
    }

    /**
     * Sets the value of the viewer property.
     * 
     * @param value
     *     allowed object is
     *     {@link PanelViewer }
     *     
     */
    public void setViewer(PanelViewer value) {
        this.viewer = value;
    }

    /**
     * Gets the value of the editor property.
     * 
     * @return
     *     possible object is
     *     {@link PanelEditor }
     *     
     */
    public PanelEditor getEditor() {
        return editor;
    }

    /**
     * Sets the value of the editor property.
     * 
     * @param value
     *     allowed object is
     *     {@link PanelEditor }
     *     
     */
    public void setEditor(PanelEditor value) {
        this.editor = value;
    }

}
