//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://axelor.com/xml/ns/object-views", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.axelor.apps.viewmanagement.objectviews;
