//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PanelRelated complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PanelRelated"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://axelor.com/xml/ns/object-views}AbstractPanel"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="field" type="{http://axelor.com/xml/ns/object-views}PanelField" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="button" type="{http://axelor.com/xml/ns/object-views}Button" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attGroup ref="{http://axelor.com/xml/ns/object-views}RelationalAttributes"/&gt;
 *       &lt;attGroup ref="{http://axelor.com/xml/ns/object-views}ExtraAttributes"/&gt;
 *       &lt;attribute name="field" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="editable" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="required" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="requiredIf" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="validIf" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="orderBy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="groupBy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="onNew" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="onChange" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="canMove" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="x-selector"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="checkbox"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;anyAttribute processContents='skip'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PanelRelated", propOrder = {
    "field",
    "button"
})
public class PanelRelated
    extends AbstractPanel
{

    protected List<PanelField> field;
    protected List<Button> button;
    @XmlAttribute(name = "field", required = true)
    protected String fieldAttribute;
    @XmlAttribute(name = "editable")
    protected Boolean editable;
    @XmlAttribute(name = "required")
    protected Boolean required;
    @XmlAttribute(name = "requiredIf")
    protected String requiredIf;
    @XmlAttribute(name = "validIf")
    protected String validIf;
    @XmlAttribute(name = "orderBy")
    protected String orderBy;
    @XmlAttribute(name = "groupBy")
    protected String groupBy;
    @XmlAttribute(name = "onNew")
    protected String onNew;
    @XmlAttribute(name = "onChange")
    protected String onChange;
    @XmlAttribute(name = "canMove")
    protected Boolean canMove;
    @XmlAttribute(name = "x-selector")
    protected String xSelector;
    @XmlAttribute(name = "target")
    @XmlSchemaType(name = "anySimpleType")
    protected String target;
    @XmlAttribute(name = "target-name")
    @XmlSchemaType(name = "anySimpleType")
    protected String targetName;
    @XmlAttribute(name = "domain")
    protected String domain;
    @XmlAttribute(name = "edit-window")
    protected String editWindow;
    @XmlAttribute(name = "form-view")
    protected String formView;
    @XmlAttribute(name = "grid-view")
    protected String gridView;
    @XmlAttribute(name = "summary-view")
    protected String summaryView;
    @XmlAttribute(name = "onSelect")
    protected String onSelect;
    @XmlAttribute(name = "canSuggest")
    protected Boolean canSuggest;
    @XmlAttribute(name = "canSelect")
    protected String canSelect;
    @XmlAttribute(name = "canNew")
    protected String canNew;
    @XmlAttribute(name = "canView")
    protected String canView;
    @XmlAttribute(name = "canEdit")
    protected String canEdit;
    @XmlAttribute(name = "canRemove")
    protected String canRemove;
    @XmlAttribute(name = "x-can-reload")
    protected Boolean xCanReload;
    @XmlAttribute(name = "x-call-onSave")
    protected Boolean xCallOnSave;
    @XmlAttribute(name = "x-search-limit")
    protected Integer xSearchLimit;
    @XmlAttribute(name = "x-color-field")
    protected String xColorField;
    @XmlAttribute(name = "x-popup-maximized")
    protected String xPopupMaximized;
    @XmlAttribute(name = "x-bind")
    protected String xBind;
    @XmlAttribute(name = "x-enum-type")
    @XmlSchemaType(name = "anySimpleType")
    protected String xEnumType;
    @XmlAttribute(name = "x-related")
    protected String xRelated;
    @XmlAttribute(name = "x-create")
    protected String xCreate;
    @XmlAttribute(name = "x-icon")
    protected String xIcon;
    @XmlAttribute(name = "x-icon-hover")
    protected String xIconHover;
    @XmlAttribute(name = "x-icon-active")
    protected String xIconActive;
    @XmlAttribute(name = "x-exclusive")
    protected Boolean xExclusive;
    @XmlAttribute(name = "x-show-icons")
    protected String xShowIcons;
    @XmlAttribute(name = "x-show-bars")
    protected Boolean xShowBars;
    @XmlAttribute(name = "x-can-copy")
    protected Boolean xCanCopy;
    @XmlAttribute(name = "x-can-export")
    protected Boolean xCanExport;
    @XmlAttribute(name = "x-direction")
    protected String xDirection;
    @XmlAttribute(name = "x-code-syntax")
    protected String xCodeSyntax;
    @XmlAttribute(name = "x-code-theme")
    protected String xCodeTheme;
    @XmlAttribute(name = "x-lite")
    protected Boolean xLite;
    @XmlAttribute(name = "x-labels")
    protected Boolean xLabels;
    @XmlAttribute(name = "x-order")
    protected String xOrder;
    @XmlAttribute(name = "x-limit")
    protected Integer xLimit;
    @XmlAttribute(name = "x-precision")
    protected BigInteger xPrecision;
    @XmlAttribute(name = "x-scale")
    protected String xScale;
    @XmlAttribute(name = "x-currency")
    protected String xCurrency;
    @XmlAttribute(name = "x-true-text")
    protected String xTrueText;
    @XmlAttribute(name = "x-false-text")
    protected String xFalseText;
    @XmlAttribute(name = "x-big")
    protected Boolean xBig;
    @XmlAttribute(name = "x-seconds")
    protected Boolean xSeconds;
    @XmlAttribute(name = "x-accept")
    protected String xAccept;
    @XmlAttribute(name = "x-preview-style")
    protected String xPreviewStyle;
    @XmlAttribute(name = "x-initial-edit-type")
    protected String xInitialEditType;
    @XmlAttribute(name = "x-hide-mode-switch")
    protected Boolean xHideModeSwitch;

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PanelField }
     * 
     * 
     */
    public List<PanelField> getField() {
        if (field == null) {
            field = new ArrayList<PanelField>();
        }
        return this.field;
    }

    /**
     * Gets the value of the button property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the button property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getButton().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Button }
     * 
     * 
     */
    public List<Button> getButton() {
        if (button == null) {
            button = new ArrayList<Button>();
        }
        return this.button;
    }

    /**
     * Gets the value of the fieldAttribute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldAttribute() {
        return fieldAttribute;
    }

    /**
     * Sets the value of the fieldAttribute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldAttribute(String value) {
        this.fieldAttribute = value;
    }

    /**
     * Gets the value of the editable property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isEditable() {
        return editable;
    }

    /**
     * Sets the value of the editable property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setEditable(Boolean value) {
        this.editable = value;
    }

    /**
     * Gets the value of the required property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRequired() {
        return required;
    }

    /**
     * Sets the value of the required property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRequired(Boolean value) {
        this.required = value;
    }

    /**
     * Gets the value of the requiredIf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequiredIf() {
        return requiredIf;
    }

    /**
     * Sets the value of the requiredIf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequiredIf(String value) {
        this.requiredIf = value;
    }

    /**
     * Gets the value of the validIf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValidIf() {
        return validIf;
    }

    /**
     * Sets the value of the validIf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValidIf(String value) {
        this.validIf = value;
    }

    /**
     * Gets the value of the orderBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderBy() {
        return orderBy;
    }

    /**
     * Sets the value of the orderBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderBy(String value) {
        this.orderBy = value;
    }

    /**
     * Gets the value of the groupBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroupBy() {
        return groupBy;
    }

    /**
     * Sets the value of the groupBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroupBy(String value) {
        this.groupBy = value;
    }

    /**
     * Gets the value of the onNew property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnNew() {
        return onNew;
    }

    /**
     * Sets the value of the onNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnNew(String value) {
        this.onNew = value;
    }

    /**
     * Gets the value of the onChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnChange() {
        return onChange;
    }

    /**
     * Sets the value of the onChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnChange(String value) {
        this.onChange = value;
    }

    /**
     * Gets the value of the canMove property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCanMove() {
        return canMove;
    }

    /**
     * Sets the value of the canMove property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanMove(Boolean value) {
        this.canMove = value;
    }

    /**
     * Gets the value of the xSelector property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXSelector() {
        return xSelector;
    }

    /**
     * Sets the value of the xSelector property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXSelector(String value) {
        this.xSelector = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTarget(String value) {
        this.target = value;
    }

    /**
     * Gets the value of the targetName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetName() {
        return targetName;
    }

    /**
     * Sets the value of the targetName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetName(String value) {
        this.targetName = value;
    }

    /**
     * Gets the value of the domain property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDomain() {
        return domain;
    }

    /**
     * Sets the value of the domain property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDomain(String value) {
        this.domain = value;
    }

    /**
     * Gets the value of the editWindow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEditWindow() {
        return editWindow;
    }

    /**
     * Sets the value of the editWindow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEditWindow(String value) {
        this.editWindow = value;
    }

    /**
     * Gets the value of the formView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormView() {
        return formView;
    }

    /**
     * Sets the value of the formView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormView(String value) {
        this.formView = value;
    }

    /**
     * Gets the value of the gridView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridView() {
        return gridView;
    }

    /**
     * Sets the value of the gridView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridView(String value) {
        this.gridView = value;
    }

    /**
     * Gets the value of the summaryView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryView() {
        return summaryView;
    }

    /**
     * Sets the value of the summaryView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryView(String value) {
        this.summaryView = value;
    }

    /**
     * Gets the value of the onSelect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnSelect() {
        return onSelect;
    }

    /**
     * Sets the value of the onSelect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnSelect(String value) {
        this.onSelect = value;
    }

    /**
     * Gets the value of the canSuggest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isCanSuggest() {
        if (canSuggest == null) {
            return true;
        } else {
            return canSuggest;
        }
    }

    /**
     * Sets the value of the canSuggest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCanSuggest(Boolean value) {
        this.canSuggest = value;
    }

    /**
     * Gets the value of the canSelect property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanSelect() {
        return canSelect;
    }

    /**
     * Sets the value of the canSelect property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanSelect(String value) {
        this.canSelect = value;
    }

    /**
     * Gets the value of the canNew property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanNew() {
        return canNew;
    }

    /**
     * Sets the value of the canNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanNew(String value) {
        this.canNew = value;
    }

    /**
     * Gets the value of the canView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanView() {
        return canView;
    }

    /**
     * Sets the value of the canView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanView(String value) {
        this.canView = value;
    }

    /**
     * Gets the value of the canEdit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanEdit() {
        return canEdit;
    }

    /**
     * Sets the value of the canEdit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanEdit(String value) {
        this.canEdit = value;
    }

    /**
     * Gets the value of the canRemove property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCanRemove() {
        return canRemove;
    }

    /**
     * Sets the value of the canRemove property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCanRemove(String value) {
        this.canRemove = value;
    }

    /**
     * Gets the value of the xCanReload property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXCanReload() {
        return xCanReload;
    }

    /**
     * Sets the value of the xCanReload property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXCanReload(Boolean value) {
        this.xCanReload = value;
    }

    /**
     * Gets the value of the xCallOnSave property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXCallOnSave() {
        return xCallOnSave;
    }

    /**
     * Sets the value of the xCallOnSave property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXCallOnSave(Boolean value) {
        this.xCallOnSave = value;
    }

    /**
     * Gets the value of the xSearchLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getXSearchLimit() {
        return xSearchLimit;
    }

    /**
     * Sets the value of the xSearchLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setXSearchLimit(Integer value) {
        this.xSearchLimit = value;
    }

    /**
     * Gets the value of the xColorField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXColorField() {
        return xColorField;
    }

    /**
     * Sets the value of the xColorField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXColorField(String value) {
        this.xColorField = value;
    }

    /**
     * Gets the value of the xPopupMaximized property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPopupMaximized() {
        return xPopupMaximized;
    }

    /**
     * Sets the value of the xPopupMaximized property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPopupMaximized(String value) {
        this.xPopupMaximized = value;
    }

    /**
     * Gets the value of the xBind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXBind() {
        return xBind;
    }

    /**
     * Sets the value of the xBind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXBind(String value) {
        this.xBind = value;
    }

    /**
     * Gets the value of the xEnumType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXEnumType() {
        return xEnumType;
    }

    /**
     * Sets the value of the xEnumType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXEnumType(String value) {
        this.xEnumType = value;
    }

    /**
     * Gets the value of the xRelated property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXRelated() {
        return xRelated;
    }

    /**
     * Sets the value of the xRelated property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXRelated(String value) {
        this.xRelated = value;
    }

    /**
     * Gets the value of the xCreate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCreate() {
        return xCreate;
    }

    /**
     * Sets the value of the xCreate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCreate(String value) {
        this.xCreate = value;
    }

    /**
     * Gets the value of the xIcon property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXIcon() {
        return xIcon;
    }

    /**
     * Sets the value of the xIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXIcon(String value) {
        this.xIcon = value;
    }

    /**
     * Gets the value of the xIconHover property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXIconHover() {
        return xIconHover;
    }

    /**
     * Sets the value of the xIconHover property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXIconHover(String value) {
        this.xIconHover = value;
    }

    /**
     * Gets the value of the xIconActive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXIconActive() {
        return xIconActive;
    }

    /**
     * Sets the value of the xIconActive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXIconActive(String value) {
        this.xIconActive = value;
    }

    /**
     * Gets the value of the xExclusive property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXExclusive() {
        return xExclusive;
    }

    /**
     * Sets the value of the xExclusive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXExclusive(Boolean value) {
        this.xExclusive = value;
    }

    /**
     * Gets the value of the xShowIcons property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXShowIcons() {
        return xShowIcons;
    }

    /**
     * Sets the value of the xShowIcons property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXShowIcons(String value) {
        this.xShowIcons = value;
    }

    /**
     * Gets the value of the xShowBars property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXShowBars() {
        return xShowBars;
    }

    /**
     * Sets the value of the xShowBars property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXShowBars(Boolean value) {
        this.xShowBars = value;
    }

    /**
     * Gets the value of the xCanCopy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXCanCopy() {
        return xCanCopy;
    }

    /**
     * Sets the value of the xCanCopy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXCanCopy(Boolean value) {
        this.xCanCopy = value;
    }

    /**
     * Gets the value of the xCanExport property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXCanExport() {
        return xCanExport;
    }

    /**
     * Sets the value of the xCanExport property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXCanExport(Boolean value) {
        this.xCanExport = value;
    }

    /**
     * Gets the value of the xDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXDirection() {
        return xDirection;
    }

    /**
     * Sets the value of the xDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXDirection(String value) {
        this.xDirection = value;
    }

    /**
     * Gets the value of the xCodeSyntax property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCodeSyntax() {
        return xCodeSyntax;
    }

    /**
     * Sets the value of the xCodeSyntax property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCodeSyntax(String value) {
        this.xCodeSyntax = value;
    }

    /**
     * Gets the value of the xCodeTheme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCodeTheme() {
        return xCodeTheme;
    }

    /**
     * Sets the value of the xCodeTheme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCodeTheme(String value) {
        this.xCodeTheme = value;
    }

    /**
     * Gets the value of the xLite property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXLite() {
        return xLite;
    }

    /**
     * Sets the value of the xLite property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXLite(Boolean value) {
        this.xLite = value;
    }

    /**
     * Gets the value of the xLabels property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXLabels() {
        return xLabels;
    }

    /**
     * Sets the value of the xLabels property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXLabels(Boolean value) {
        this.xLabels = value;
    }

    /**
     * Gets the value of the xOrder property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXOrder() {
        return xOrder;
    }

    /**
     * Sets the value of the xOrder property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXOrder(String value) {
        this.xOrder = value;
    }

    /**
     * Gets the value of the xLimit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getXLimit() {
        return xLimit;
    }

    /**
     * Sets the value of the xLimit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setXLimit(Integer value) {
        this.xLimit = value;
    }

    /**
     * Gets the value of the xPrecision property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getXPrecision() {
        return xPrecision;
    }

    /**
     * Sets the value of the xPrecision property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setXPrecision(BigInteger value) {
        this.xPrecision = value;
    }

    /**
     * Gets the value of the xScale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXScale() {
        return xScale;
    }

    /**
     * Sets the value of the xScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXScale(String value) {
        this.xScale = value;
    }

    /**
     * Gets the value of the xCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXCurrency() {
        return xCurrency;
    }

    /**
     * Sets the value of the xCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXCurrency(String value) {
        this.xCurrency = value;
    }

    /**
     * Gets the value of the xTrueText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXTrueText() {
        return xTrueText;
    }

    /**
     * Sets the value of the xTrueText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXTrueText(String value) {
        this.xTrueText = value;
    }

    /**
     * Gets the value of the xFalseText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXFalseText() {
        return xFalseText;
    }

    /**
     * Sets the value of the xFalseText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXFalseText(String value) {
        this.xFalseText = value;
    }

    /**
     * Gets the value of the xBig property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXBig() {
        return xBig;
    }

    /**
     * Sets the value of the xBig property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXBig(Boolean value) {
        this.xBig = value;
    }

    /**
     * Gets the value of the xSeconds property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXSeconds() {
        return xSeconds;
    }

    /**
     * Sets the value of the xSeconds property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXSeconds(Boolean value) {
        this.xSeconds = value;
    }

    /**
     * Gets the value of the xAccept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXAccept() {
        return xAccept;
    }

    /**
     * Sets the value of the xAccept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXAccept(String value) {
        this.xAccept = value;
    }

    /**
     * Gets the value of the xPreviewStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPreviewStyle() {
        if (xPreviewStyle == null) {
            return "tab";
        } else {
            return xPreviewStyle;
        }
    }

    /**
     * Sets the value of the xPreviewStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPreviewStyle(String value) {
        this.xPreviewStyle = value;
    }

    /**
     * Gets the value of the xInitialEditType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXInitialEditType() {
        if (xInitialEditType == null) {
            return "markdown";
        } else {
            return xInitialEditType;
        }
    }

    /**
     * Sets the value of the xInitialEditType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXInitialEditType(String value) {
        this.xInitialEditType = value;
    }

    /**
     * Gets the value of the xHideModeSwitch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isXHideModeSwitch() {
        if (xHideModeSwitch == null) {
            return false;
        } else {
            return xHideModeSwitch;
        }
    }

    /**
     * Sets the value of the xHideModeSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXHideModeSwitch(Boolean value) {
        this.xHideModeSwitch = value;
    }

}
