//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PanelMail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PanelMail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://axelor.com/xml/ns/object-views}AbstractPanel"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mail-messages"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="limit" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="mail-followers" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='skip'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PanelMail", propOrder = {
    "mailMessages",
    "mailFollowers"
})
public class PanelMail
    extends AbstractPanel
{

    @XmlElement(name = "mail-messages", required = true)
    protected MailMessages mailMessages;
    @XmlElement(name = "mail-followers")
    protected Object mailFollowers;

    /**
     * Gets the value of the mailMessages property.
     * 
     * @return
     *     possible object is
     *     {@link MailMessages }
     *     
     */
    public MailMessages getMailMessages() {
        return mailMessages;
    }

    /**
     * Sets the value of the mailMessages property.
     * 
     * @param value
     *     allowed object is
     *     {@link MailMessages }
     *     
     */
    public void setMailMessages(MailMessages value) {
        this.mailMessages = value;
    }

    /**
     * Gets the value of the mailFollowers property.
     * 
     * @return
     *     possible object is
     *     {@link Object }
     *     
     */
    public Object getMailFollowers() {
        return mailFollowers;
    }

    /**
     * Sets the value of the mailFollowers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Object }
     *     
     */
    public void setMailFollowers(Object value) {
        this.mailFollowers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="limit" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class MailMessages {

        @XmlAttribute(name = "limit")
        protected Integer limit;

        /**
         * Gets the value of the limit property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getLimit() {
            return limit;
        }

        /**
         * Sets the value of the limit property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setLimit(Integer value) {
            this.limit = value;
        }

    }

}
