//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PanelEditor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PanelEditor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://axelor.com/xml/ns/object-views}AbstractPanel"&gt;
 *       &lt;choice maxOccurs="unbounded" minOccurs="0"&gt;
 *         &lt;element name="field" type="{http://axelor.com/xml/ns/object-views}BaseField"/&gt;
 *         &lt;element name="button" type="{http://axelor.com/xml/ns/object-views}Button"/&gt;
 *         &lt;element name="spacer" type="{http://axelor.com/xml/ns/object-views}Spacer"/&gt;
 *         &lt;element name="separator" type="{http://axelor.com/xml/ns/object-views}Separator"/&gt;
 *         &lt;element name="label" type="{http://axelor.com/xml/ns/object-views}Label"/&gt;
 *         &lt;element name="panel"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://axelor.com/xml/ns/object-views}PanelEditor"&gt;
 *                 &lt;anyAttribute processContents='skip'/&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/choice&gt;
 *       &lt;attribute name="layout" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="onNew" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="x-viewer" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="x-show-titles" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="x-show-on-new" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;anyAttribute processContents='skip'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PanelEditor", propOrder = {
    "fieldOrButtonOrSpacer"
})
@XmlSeeAlso({
    PanelEditor.Panel.class
})
public class PanelEditor
    extends AbstractPanel
{

    @XmlElements({
        @XmlElement(name = "field", type = BaseField.class),
        @XmlElement(name = "button", type = Button.class),
        @XmlElement(name = "spacer", type = Spacer.class),
        @XmlElement(name = "separator", type = Separator.class),
        @XmlElement(name = "label", type = Label.class),
        @XmlElement(name = "panel", type = Panel.class)
    })
    protected List<SimpleWidget> fieldOrButtonOrSpacer;
    @XmlAttribute(name = "layout")
    protected String layout;
    @XmlAttribute(name = "onNew")
    protected String onNew;
    @XmlAttribute(name = "x-viewer")
    protected Boolean xViewer;
    @XmlAttribute(name = "x-show-titles")
    protected Boolean xShowTitles;
    @XmlAttribute(name = "x-show-on-new")
    protected Boolean xShowOnNew;

    /**
     * Gets the value of the fieldOrButtonOrSpacer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fieldOrButtonOrSpacer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFieldOrButtonOrSpacer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BaseField }
     * {@link Button }
     * {@link Spacer }
     * {@link Separator }
     * {@link Label }
     * {@link Panel }
     * 
     * 
     */
    public List<SimpleWidget> getFieldOrButtonOrSpacer() {
        if (fieldOrButtonOrSpacer == null) {
            fieldOrButtonOrSpacer = new ArrayList<SimpleWidget>();
        }
        return this.fieldOrButtonOrSpacer;
    }

    /**
     * Gets the value of the layout property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLayout() {
        return layout;
    }

    /**
     * Sets the value of the layout property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLayout(String value) {
        this.layout = value;
    }

    /**
     * Gets the value of the onNew property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOnNew() {
        return onNew;
    }

    /**
     * Sets the value of the onNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOnNew(String value) {
        this.onNew = value;
    }

    /**
     * Gets the value of the xViewer property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXViewer() {
        return xViewer;
    }

    /**
     * Sets the value of the xViewer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXViewer(Boolean value) {
        this.xViewer = value;
    }

    /**
     * Gets the value of the xShowTitles property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXShowTitles() {
        return xShowTitles;
    }

    /**
     * Sets the value of the xShowTitles property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXShowTitles(Boolean value) {
        this.xShowTitles = value;
    }

    /**
     * Gets the value of the xShowOnNew property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isXShowOnNew() {
        return xShowOnNew;
    }

    /**
     * Sets the value of the xShowOnNew property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setXShowOnNew(Boolean value) {
        this.xShowOnNew = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://axelor.com/xml/ns/object-views}PanelEditor"&gt;
     *       &lt;anyAttribute processContents='skip'/&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Panel
        extends PanelEditor
    {


    }

}
