//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchSelectWhere complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchSelectWhere"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="input" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="field" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="matchStyle" default="equals"&gt;
 *                   &lt;simpleType&gt;
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *                       &lt;enumeration value="startsWith"/&gt;
 *                       &lt;enumeration value="endsWith"/&gt;
 *                       &lt;enumeration value="contains"/&gt;
 *                       &lt;enumeration value="equals"/&gt;
 *                       &lt;enumeration value="notEquals"/&gt;
 *                       &lt;enumeration value="lessThan"/&gt;
 *                       &lt;enumeration value="greaterThan"/&gt;
 *                       &lt;enumeration value="lessOrEqual"/&gt;
 *                       &lt;enumeration value="greaterOrEqual"/&gt;
 *                     &lt;/restriction&gt;
 *                   &lt;/simpleType&gt;
 *                 &lt;/attribute&gt;
 *                 &lt;attribute name="if" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="expr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="where" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;extension base="{http://axelor.com/xml/ns/object-views}SearchSelectWhere"&gt;
 *               &lt;/extension&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="match" default="all"&gt;
 *         &lt;simpleType&gt;
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *             &lt;enumeration value="all"/&gt;
 *             &lt;enumeration value="any"/&gt;
 *           &lt;/restriction&gt;
 *         &lt;/simpleType&gt;
 *       &lt;/attribute&gt;
 *       &lt;attribute name="showArchived" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *       &lt;attribute name="if" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchSelectWhere", propOrder = {
    "input",
    "where"
})
@XmlSeeAlso({
    SearchSelectWhere.Where.class,
    SearchSelectWhereFilter.class
})
public class SearchSelectWhere {

    protected List<Input> input;
    protected List<Where> where;
    @XmlAttribute(name = "match")
    protected String match;
    @XmlAttribute(name = "showArchived")
    protected Boolean showArchived;
    @XmlAttribute(name = "if")
    protected String _if;

    /**
     * Gets the value of the input property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the input property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInput().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Input }
     * 
     * 
     */
    public List<Input> getInput() {
        if (input == null) {
            input = new ArrayList<Input>();
        }
        return this.input;
    }

    /**
     * Gets the value of the where property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the where property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWhere().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Where }
     * 
     * 
     */
    public List<Where> getWhere() {
        if (where == null) {
            where = new ArrayList<Where>();
        }
        return this.where;
    }

    /**
     * Gets the value of the match property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatch() {
        if (match == null) {
            return "all";
        } else {
            return match;
        }
    }

    /**
     * Sets the value of the match property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatch(String value) {
        this.match = value;
    }

    /**
     * Gets the value of the showArchived property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isShowArchived() {
        if (showArchived == null) {
            return false;
        } else {
            return showArchived;
        }
    }

    /**
     * Sets the value of the showArchived property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setShowArchived(Boolean value) {
        this.showArchived = value;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIf(String value) {
        this._if = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="field" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="matchStyle" default="equals"&gt;
     *         &lt;simpleType&gt;
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
     *             &lt;enumeration value="startsWith"/&gt;
     *             &lt;enumeration value="endsWith"/&gt;
     *             &lt;enumeration value="contains"/&gt;
     *             &lt;enumeration value="equals"/&gt;
     *             &lt;enumeration value="notEquals"/&gt;
     *             &lt;enumeration value="lessThan"/&gt;
     *             &lt;enumeration value="greaterThan"/&gt;
     *             &lt;enumeration value="lessOrEqual"/&gt;
     *             &lt;enumeration value="greaterOrEqual"/&gt;
     *           &lt;/restriction&gt;
     *         &lt;/simpleType&gt;
     *       &lt;/attribute&gt;
     *       &lt;attribute name="if" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="expr" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Input {

        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "field", required = true)
        protected String field;
        @XmlAttribute(name = "matchStyle")
        protected String matchStyle;
        @XmlAttribute(name = "if")
        protected String _if;
        @XmlAttribute(name = "expr")
        protected String expr;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the field property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getField() {
            return field;
        }

        /**
         * Sets the value of the field property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setField(String value) {
            this.field = value;
        }

        /**
         * Gets the value of the matchStyle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMatchStyle() {
            if (matchStyle == null) {
                return "equals";
            } else {
                return matchStyle;
            }
        }

        /**
         * Sets the value of the matchStyle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMatchStyle(String value) {
            this.matchStyle = value;
        }

        /**
         * Gets the value of the if property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIf() {
            return _if;
        }

        /**
         * Sets the value of the if property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIf(String value) {
            this._if = value;
        }

        /**
         * Gets the value of the expr property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExpr() {
            return expr;
        }

        /**
         * Sets the value of the expr property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExpr(String value) {
            this.expr = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;extension base="{http://axelor.com/xml/ns/object-views}SearchSelectWhere"&gt;
     *     &lt;/extension&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Where
        extends SearchSelectWhere
    {


    }

}
