//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Search complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Search"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://axelor.com/xml/ns/object-views}SimpleView"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="search-fields"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="field" type="{http://axelor.com/xml/ns/object-views}BaseSearchField" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="result-fields"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="hilite" type="{http://axelor.com/xml/ns/object-views}Hilite" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                   &lt;element name="field" type="{http://axelor.com/xml/ns/object-views}SearchResultField" maxOccurs="unbounded"/&gt;
 *                   &lt;element name="button" type="{http://axelor.com/xml/ns/object-views}GridButton" maxOccurs="unbounded" minOccurs="0"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="select" type="{http://axelor.com/xml/ns/object-views}SearchSelect" maxOccurs="unbounded"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="limit" use="required" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="search-form" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Search", propOrder = {
    "searchFields",
    "resultFields",
    "select"
})
public class Search
    extends SimpleView
{

    @XmlElement(name = "search-fields", required = true)
    protected SearchFields searchFields;
    @XmlElement(name = "result-fields", required = true)
    protected ResultFields resultFields;
    @XmlElement(required = true)
    protected List<SearchSelect> select;
    @XmlAttribute(name = "limit", required = true)
    protected int limit;
    @XmlAttribute(name = "search-form")
    protected String searchForm;

    /**
     * Gets the value of the searchFields property.
     * 
     * @return
     *     possible object is
     *     {@link SearchFields }
     *     
     */
    public SearchFields getSearchFields() {
        return searchFields;
    }

    /**
     * Sets the value of the searchFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchFields }
     *     
     */
    public void setSearchFields(SearchFields value) {
        this.searchFields = value;
    }

    /**
     * Gets the value of the resultFields property.
     * 
     * @return
     *     possible object is
     *     {@link ResultFields }
     *     
     */
    public ResultFields getResultFields() {
        return resultFields;
    }

    /**
     * Sets the value of the resultFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultFields }
     *     
     */
    public void setResultFields(ResultFields value) {
        this.resultFields = value;
    }

    /**
     * Gets the value of the select property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the select property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelect().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SearchSelect }
     * 
     * 
     */
    public List<SearchSelect> getSelect() {
        if (select == null) {
            select = new ArrayList<SearchSelect>();
        }
        return this.select;
    }

    /**
     * Gets the value of the limit property.
     * 
     */
    public int getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     */
    public void setLimit(int value) {
        this.limit = value;
    }

    /**
     * Gets the value of the searchForm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchForm() {
        return searchForm;
    }

    /**
     * Sets the value of the searchForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchForm(String value) {
        this.searchForm = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="hilite" type="{http://axelor.com/xml/ns/object-views}Hilite" maxOccurs="unbounded" minOccurs="0"/&gt;
     *         &lt;element name="field" type="{http://axelor.com/xml/ns/object-views}SearchResultField" maxOccurs="unbounded"/&gt;
     *         &lt;element name="button" type="{http://axelor.com/xml/ns/object-views}GridButton" maxOccurs="unbounded" minOccurs="0"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "hilite",
        "field",
        "button"
    })
    public static class ResultFields {

        protected List<Hilite> hilite;
        @XmlElement(required = true)
        protected List<SearchResultField> field;
        protected List<GridButton> button;

        /**
         * Gets the value of the hilite property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hilite property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHilite().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Hilite }
         * 
         * 
         */
        public List<Hilite> getHilite() {
            if (hilite == null) {
                hilite = new ArrayList<Hilite>();
            }
            return this.hilite;
        }

        /**
         * Gets the value of the field property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the field property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link SearchResultField }
         * 
         * 
         */
        public List<SearchResultField> getField() {
            if (field == null) {
                field = new ArrayList<SearchResultField>();
            }
            return this.field;
        }

        /**
         * Gets the value of the button property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the button property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getButton().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GridButton }
         * 
         * 
         */
        public List<GridButton> getButton() {
            if (button == null) {
                button = new ArrayList<GridButton>();
            }
            return this.button;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="field" type="{http://axelor.com/xml/ns/object-views}BaseSearchField" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "field"
    })
    public static class SearchFields {

        @XmlElement(required = true)
        protected List<BaseSearchField> field;

        /**
         * Gets the value of the field property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the field property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getField().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link BaseSearchField }
         * 
         * 
         */
        public List<BaseSearchField> getField() {
            if (field == null) {
                field = new ArrayList<BaseSearchField>();
            }
            return this.field;
        }

    }

}
