//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.31 at 06:37:00 PM ALMT 
//


package com.axelor.apps.viewmanagement.objectviews;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Defines search criteria per object and maps the object fields to the result fields.
 *             
 * 
 * <p>Java class for SearchSelect complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchSelect"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="field" maxOccurs="unbounded"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="as" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                 &lt;attribute name="enum-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *                 &lt;attribute name="selection" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="where" type="{http://axelor.com/xml/ns/object-views}SearchSelectWhereFilter"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="model" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="title" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="view-title" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="selected" type="{http://www.w3.org/2001/XMLSchema}boolean" /&gt;
 *       &lt;attribute name="orderBy" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="if" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="form-view" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="grid-view" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="limit" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *       &lt;attribute name="distinct" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchSelect", propOrder = {
    "field",
    "where"
})
public class SearchSelect {

    @XmlElement(required = true)
    protected List<Field> field;
    @XmlElement(required = true)
    protected SearchSelectWhereFilter where;
    @XmlAttribute(name = "model", required = true)
    protected String model;
    @XmlAttribute(name = "title")
    protected String title;
    @XmlAttribute(name = "view-title")
    protected String viewTitle;
    @XmlAttribute(name = "selected")
    protected Boolean selected;
    @XmlAttribute(name = "orderBy")
    protected String orderBy;
    @XmlAttribute(name = "if")
    protected String _if;
    @XmlAttribute(name = "form-view")
    protected String formView;
    @XmlAttribute(name = "grid-view")
    protected String gridView;
    @XmlAttribute(name = "limit")
    protected Integer limit;
    @XmlAttribute(name = "distinct")
    protected Boolean distinct;

    /**
     * Gets the value of the field property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the field property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getField().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Field }
     * 
     * 
     */
    public List<Field> getField() {
        if (field == null) {
            field = new ArrayList<Field>();
        }
        return this.field;
    }

    /**
     * Gets the value of the where property.
     * 
     * @return
     *     possible object is
     *     {@link SearchSelectWhereFilter }
     *     
     */
    public SearchSelectWhereFilter getWhere() {
        return where;
    }

    /**
     * Sets the value of the where property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchSelectWhereFilter }
     *     
     */
    public void setWhere(SearchSelectWhereFilter value) {
        this.where = value;
    }

    /**
     * Gets the value of the model property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getModel() {
        return model;
    }

    /**
     * Sets the value of the model property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setModel(String value) {
        this.model = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the viewTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getViewTitle() {
        return viewTitle;
    }

    /**
     * Sets the value of the viewTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setViewTitle(String value) {
        this.viewTitle = value;
    }

    /**
     * Gets the value of the selected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSelected() {
        return selected;
    }

    /**
     * Sets the value of the selected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelected(Boolean value) {
        this.selected = value;
    }

    /**
     * Gets the value of the orderBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderBy() {
        return orderBy;
    }

    /**
     * Sets the value of the orderBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderBy(String value) {
        this.orderBy = value;
    }

    /**
     * Gets the value of the if property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIf() {
        return _if;
    }

    /**
     * Sets the value of the if property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIf(String value) {
        this._if = value;
    }

    /**
     * Gets the value of the formView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormView() {
        return formView;
    }

    /**
     * Sets the value of the formView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormView(String value) {
        this.formView = value;
    }

    /**
     * Gets the value of the gridView property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGridView() {
        return gridView;
    }

    /**
     * Sets the value of the gridView property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGridView(String value) {
        this.gridView = value;
    }

    /**
     * Gets the value of the limit property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getLimit() {
        return limit;
    }

    /**
     * Sets the value of the limit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setLimit(Integer value) {
        this.limit = value;
    }

    /**
     * Gets the value of the distinct property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDistinct() {
        if (distinct == null) {
            return false;
        } else {
            return distinct;
        }
    }

    /**
     * Sets the value of the distinct property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDistinct(Boolean value) {
        this.distinct = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="as" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *       &lt;attribute name="enum-type" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *       &lt;attribute name="selection" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" /&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class Field {

        @XmlAttribute(name = "name", required = true)
        protected String name;
        @XmlAttribute(name = "as", required = true)
        protected String as;
        @XmlAttribute(name = "enum-type")
        @XmlSchemaType(name = "anySimpleType")
        protected String enumType;
        @XmlAttribute(name = "selection")
        @XmlSchemaType(name = "anySimpleType")
        protected String selection;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the as property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAs() {
            return as;
        }

        /**
         * Sets the value of the as property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAs(String value) {
            this.as = value;
        }

        /**
         * Gets the value of the enumType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEnumType() {
            return enumType;
        }

        /**
         * Sets the value of the enumType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEnumType(String value) {
            this.enumType = value;
        }

        /**
         * Gets the value of the selection property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSelection() {
            return selection;
        }

        /**
         * Sets the value of the selection property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSelection(String value) {
            this.selection = value;
        }

    }

}
